export const CANDLESTICK_CHART_PADDING_LEFT = 12;
export const CANDLESTICK_CHART_PADDING_RIGHT = 12;
export const CANDLESTICK_CHART_PADDING_TOP = 12;
export const CANDLESTICK_CHART_PADDING_BOTTOM = 12;
